

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/software
    password: 123456
    hikari:
      minimum-idle: 2
      maximum-pool-size: 6
      idle-timeout: 60000
  # mvc:
  #   view:
  #     prefix: /WEB-INF/
#mybatis:
#  type-aliases-package: com.bus.entity
#  mapper-locations:
#    classpath: com/bus/mapper/*.xml

